version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - postgres
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  minio:
    image: "minio/minio:RELEASE.2024-10-29T16-01-48Z"
    restart: always
    container_name: e-commerce_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: minio server /data/minio --console-address ":9001"
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      - "discovery.type=single-node"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=password"
      - "xpack.security.enabled=true"
    ports: ["9200:9200", "9300:9300"]
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"
    #       memory: 50M
    #     reservations:
    #       cpus: "0.25"
    #       memory: 20M

volumes:
  db_data:
